"""W-46: Chebyshev fit for the peeled log1p tail on u in [0, 0.5].

log1p(w) = anchor + [u - u^2/2 + u^3 * S(u)],  u = (w - a)/(1 + a),
with a = 0 if w < 0.5 else 0.5 (anchor = log1p(a), a double constant).
S(u) = (log1p(u) - u + u^2/2) / u^3, analytic on [-1, inf) -> fast
Chebyshev decay on [0, 0.5]. Degrees: 16 (exact-grade candidate),
13, 10 (approximate arms). Emits scratch/w46/log1p_poly.h.
"""
import mpmath as mp

mp.mp.dps = 60
A, B = mp.mpf("0"), mp.mpf("0.5")

def S(u):
    if u == 0:
        return mp.mpf(1) / 3
    return (mp.log1p(u) - u + u * u / 2) / u ** 3

def cheb_coeffs(N, M):
    # Chebyshev coefficients of S on [A,B] via N-node interpolation (N-1 roots), keep M+1
    c = []
    for k in range(M + 1):
        s = mp.mpf(0)
        for j in range(1, N + 1):
            th = mp.pi * (j - mp.mpf("0.5")) / N
            z = mp.cos(th)
            u = (B - A) / 2 * z + (A + B) / 2
            s += S(u) * mp.cos(k * th)
        c.append(s / N if k == 0 else 2 * s / N)
    return c

def poly_eval(c, z):  # Clenshaw in mp
    b2 = mp.mpf(0); b1 = mp.mpf(0)
    zz = 2 * z
    for ck in reversed(c[1:]):
        b2, b1 = b1, ck + zz * b1 - b2
    return c[0] + z * b1 - b2

def maxerr(c):
    # dense check in mp arithmetic (fit error only, no double rounding)
    err = mp.mpf(0)
    n = 4097
    for i in range(n):
        u = A + (B - A) * i / (n - 1)
        z = (2 * u - (A + B)) / (B - A)
        # evaluate truncated series
        b2 = mp.mpf(0); b1 = mp.mpf(0)
        zz = 2 * z
        for ck in reversed(c[1:]):
            b2, b1 = b1, ck + zz * b1 - b2
        val = c[0] + z * b1 - b2
        err = max(err, abs(val - S(u)))
    return err

out = ["// auto-generated by scratch/w46/fit_log1p.py (mpmath, 60 dps) — do not edit",
       "#pragma once", "", "namespace w46 {", ""
       "constexpr double LN1P_HALF = 0.40546510810816438197801311546434913657199042346249419;\n"]; 
for D in (16, 13, 10):
    c = cheb_coeffs(512, D)
    e = maxerr(c)
    print(f"degree {D}: max fit error on S = {mp.nstr(e, 4)}  "
          f"(~2^{mp.nstr(mp.floor(mp.log(e,2)),3)}; on log1p scale <= u^3*err <= {mp.nstr(0.125*e,3)})")
    out.append(f"// degree {D}: |fit err| on S = {mp.nstr(e, 4)}")
    out.append(f"inline constexpr double LOG1P_S{D}[{D + 1}] = {{")
    out.append(",\n".join(f"    {mp.nstr(ck, 21)}" for ck in c))
    out.append("};")
    out.append("")
out.append("}  // namespace w46")
open("/home/m0hawk/Documents/apin/stan/scratch/w46/log1p_poly.h", "w").write("\n".join(out) + "\n")
print("wrote scratch/w46/log1p_poly.h")
