// Code generated by stanc v2.39.0
#include <stan/model/model_header.hpp>
#include <stan/math/rev/prob/pcm_lpdf_gathered.hpp>
namespace gpcm_latent_reg_irt_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 96> locations_array__ =
  {" (found before start of program)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 72, column 2 to column 27)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 73, column 2 to column 31)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 74, column 2 to column 18)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 75, column 2 to column 23)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 78, column 2 to column 22)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 93, column 2 to column 19)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 79, column 2 to column 35)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 80, column 2 to column 37)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 94, column 2 to column 64)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 95, column 2 to line 96, column 44)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 83, column 2 to column 26)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 84, column 2 to column 37)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 85, column 2 to column 40)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 86, column 2 to column 34)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 88, column 4 to line 89, column 55)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 87, column 19 to line 90, column 3)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 87, column 2 to line 90, column 3)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 40, column 2 to column 17)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 41, column 2 to column 17)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 42, column 2 to column 17)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 43, column 8 to column 9)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 43, column 2 to column 36)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 44, column 8 to column 9)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 44, column 2 to column 36)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 45, column 8 to column 9)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 45, column 2 to column 26)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 46, column 2 to column 17)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 47, column 9 to column 10)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 47, column 12 to column 13)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 47, column 2 to column 17)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 50, column 8 to column 9)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 50, column 2 to column 17)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 51, column 8 to column 9)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 51, column 2 to column 19)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 52, column 12 to column 13)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 52, column 2 to column 19)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 53, column 9 to column 10)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 53, column 12 to column 13)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 53, column 2 to column 21)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 54, column 2 to column 22)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 57, column 6 to column 22)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 56, column 25 to line 58, column 5)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 56, column 4 to line 58, column 5)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 55, column 19 to line 59, column 3)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 55, column 2 to line 59, column 3)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 60, column 2 to column 13)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 62, column 4 to column 35)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 61, column 19 to line 63, column 3)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 61, column 2 to line 63, column 3)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 64, column 2 to column 30)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 67, column 6 to column 54)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 66, column 21 to line 68, column 5)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 66, column 4 to line 68, column 5)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 65, column 19 to line 69, column 3)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 65, column 2 to line 69, column 3)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 72, column 18 to column 19)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 73, column 9 to column 19)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 74, column 9 to column 10)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 75, column 9 to column 10)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 78, column 9 to column 15)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 93, column 9 to column 10)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 3, column 11 to column 25)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 3, column 4 to column 36)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 4, column 11 to column 25)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 4, column 4 to column 33)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 5, column 4 to column 60)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 6, column 4 to column 46)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 7, column 4 to column 43)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 2, column 43 to line 8, column 3)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 10, column 4 to column 15)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 11, column 4 to column 15)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 12, column 4 to column 21)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 13, column 14 to column 21)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 13, column 4 to column 27)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 14, column 4 to column 18)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 15, column 4 to column 18)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 19, column 8 to column 39)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 20, column 8 to column 39)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 21, column 8 to column 25)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 23, column 10 to column 77)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 22, column 31 to line 24, column 9)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 22, column 8 to line 24, column 9)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 31, column 10 to column 46)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 32, column 10 to column 48)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 29, column 15 to line 33, column 9)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 27, column 10 to column 46)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 28, column 10 to column 36)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 25, column 37 to line 29, column 9)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 25, column 8 to line 33, column 9)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 17, column 29 to line 34, column 7)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 17, column 6 to line 34, column 7)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 16, column 21 to line 35, column 5)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 16, column 4 to line 35, column 5)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 36, column 4 to column 15)",
  " (in '/home/m0hawk/Documents/apin/stan/scratch/w80/model_gpcm_latent_reg_irt/gpcm_latent_reg_irt.stan', line 9, column 38 to line 37, column 3)"};
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_integral<T0__>,
                              stan::math::disjunction<stan::is_autodiff_scalar<T1__>,
                                stan::is_floating_point<T1__>>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>>* = nullptr>
stan::return_type_t<T1__, stan::base_type_t<T2__>>
pcm(const T0__& y, const T1__& theta, const T2__& beta_arg__, std::ostream*
    pstream__);
template <typename T0__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,-1>
obtain_adjustments(const T0__& W_arg__, std::ostream* pstream__);
// real pcm(int, real, vector)
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_integral<T0__>,
                              stan::math::disjunction<stan::is_autodiff_scalar<T1__>,
                                stan::is_floating_point<T1__>>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>>*>
stan::return_type_t<T1__, stan::base_type_t<T2__>>
pcm(const T0__& y, const T1__& theta, const T2__& beta_arg__, std::ostream*
    pstream__) {
  using local_scalar_t__ = stan::return_type_t<T1__, stan::base_type_t<T2__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& beta = stan::math::to_ref(beta_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 62;
    stan::math::validate_non_negative_index("unsummed", "rows(beta) + 1",
      (stan::math::rows(beta) + 1));
    Eigen::Matrix<local_scalar_t__,-1,1> unsummed =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant((stan::math::rows(beta)
        + 1), DUMMY_VAR__);
    current_statement__ = 64;
    stan::math::validate_non_negative_index("probs", "rows(beta) + 1",
      (stan::math::rows(beta) + 1));
    Eigen::Matrix<local_scalar_t__,-1,1> probs =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant((stan::math::rows(beta)
        + 1), DUMMY_VAR__);
    current_statement__ = 66;
    stan::model::assign(unsummed,
      stan::math::append_row(stan::math::rep_vector(0.0, 1),
        stan::math::subtract(theta, beta)), "assigning variable unsummed");
    current_statement__ = 67;
    stan::model::assign(probs,
      stan::math::softmax(stan::math::cumulative_sum(unsummed)),
      "assigning variable probs");
    current_statement__ = 68;
    return stan::math::categorical_lpmf<false>((y + 1), probs);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// matrix obtain_adjustments(matrix)
template <typename T0__,
          stan::require_all_t<stan::is_eigen_matrix_dynamic<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::return_type_t<stan::base_type_t<T0__>>,-1,-1>
obtain_adjustments(const T0__& W_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::return_type_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& W = stan::math::to_ref(W_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ min_w = DUMMY_VAR__;
    local_scalar_t__ max_w = DUMMY_VAR__;
    int minmax_count = std::numeric_limits<int>::min();
    current_statement__ = 73;
    stan::math::validate_non_negative_index("adj", "cols(W)",
      stan::math::cols(W));
    Eigen::Matrix<local_scalar_t__,-1,-1> adj =
      Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(2, stan::math::cols(W),
        DUMMY_VAR__);
    current_statement__ = 75;
    stan::model::assign(adj, 0, "assigning variable adj",
      stan::model::index_uni(1), stan::model::index_uni(1));
    current_statement__ = 76;
    stan::model::assign(adj, 1, "assigning variable adj",
      stan::model::index_uni(2), stan::model::index_uni(1));
    current_statement__ = 93;
    if (stan::math::logical_gt(stan::math::cols(W), 1)) {
      current_statement__ = 91;
      for (int k = 2; k <= stan::math::cols(W); ++k) {
        current_statement__ = 77;
        min_w = stan::math::min(
                  stan::model::rvalue(W, "W",
                    stan::model::index_min_max(1, stan::math::rows(W)),
                    stan::model::index_uni(k)));
        current_statement__ = 78;
        max_w = stan::math::max(
                  stan::model::rvalue(W, "W",
                    stan::model::index_min_max(1, stan::math::rows(W)),
                    stan::model::index_uni(k)));
        current_statement__ = 79;
        minmax_count = 0;
        current_statement__ = 82;
        for (int j = 1; j <= stan::math::rows(W); ++j) {
          current_statement__ = 80;
          minmax_count = (stan::math::primitive_value(
                            stan::math::logical_eq((minmax_count +
                              stan::model::rvalue(W, "W",
                                stan::model::index_uni(j),
                                stan::model::index_uni(k))), min_w))
            ||
            stan::math::primitive_value(
              stan::math::logical_eq(
                stan::model::rvalue(W, "W", stan::model::index_uni(j),
                  stan::model::index_uni(k)), max_w)));
        }
        current_statement__ = 89;
        if (stan::math::logical_eq(minmax_count, stan::math::rows(W))) {
          current_statement__ = 86;
          stan::model::assign(adj,
            stan::math::mean(
              stan::model::rvalue(W, "W",
                stan::model::index_min_max(1, stan::math::rows(W)),
                stan::model::index_uni(k))), "assigning variable adj",
            stan::model::index_uni(1), stan::model::index_uni(k));
          current_statement__ = 87;
          stan::model::assign(adj, (max_w - min_w), "assigning variable adj",
            stan::model::index_uni(2), stan::model::index_uni(k));
        } else {
          current_statement__ = 83;
          stan::model::assign(adj,
            stan::math::mean(
              stan::model::rvalue(W, "W",
                stan::model::index_min_max(1, stan::math::rows(W)),
                stan::model::index_uni(k))), "assigning variable adj",
            stan::model::index_uni(1), stan::model::index_uni(k));
          current_statement__ = 84;
          stan::model::assign(adj,
            (stan::math::sd(
               stan::model::rvalue(W, "W",
                 stan::model::index_min_max(1, stan::math::rows(W)),
                 stan::model::index_uni(k))) * 2), "assigning variable adj",
            stan::model::index_uni(2), stan::model::index_uni(k));
        }
      }
    }
    current_statement__ = 94;
    return adj;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
class gpcm_latent_reg_irt_model final : public model_base_crtp<gpcm_latent_reg_irt_model> {
 private:
  int I;
  int J;
  int N;
  std::vector<int> ii;
  std::vector<int> jj;
  std::vector<int> y;
  int K;
  Eigen::Matrix<double,-1,-1> W_data__;
  std::vector<int> m;
  std::vector<int> pos;
  Eigen::Matrix<double,-1,-1> adj_data__;
  Eigen::Matrix<double,-1,-1> W_adj_data__;
  int beta_free_1dim__;
  int beta_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> W{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> adj{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> W_adj{nullptr, 0, 0};
 public:
  ~gpcm_latent_reg_irt_model() {}
  gpcm_latent_reg_irt_model(stan::io::var_context& context__, unsigned int
                            random_seed__ = 0, std::ostream*
                            pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "gpcm_latent_reg_irt_model_namespace::gpcm_latent_reg_irt_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 18;
      context__.validate_dims("data initialization", "I", "int",
        std::vector<size_t>{});
      I = std::numeric_limits<int>::min();
      current_statement__ = 18;
      I = context__.vals_i("I")[(1 - 1)];
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "I", I, 1);
      current_statement__ = 19;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 19;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 19;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 20;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 20;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 21;
      stan::math::validate_non_negative_index("ii", "N", N);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "ii", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      ii = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 22;
      ii = context__.vals_i("ii");
      current_statement__ = 22;
      stan::math::check_greater_or_equal(function__, "ii", ii, 1);
      current_statement__ = 22;
      stan::math::check_less_or_equal(function__, "ii", ii, I);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("jj", "N", N);
      current_statement__ = 24;
      context__.validate_dims("data initialization", "jj", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      jj = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 24;
      jj = context__.vals_i("jj");
      current_statement__ = 24;
      stan::math::check_greater_or_equal(function__, "jj", jj, 1);
      current_statement__ = 24;
      stan::math::check_less_or_equal(function__, "jj", jj, J);
      current_statement__ = 25;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      y = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 26;
      y = context__.vals_i("y");
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "y", y, 0);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 27;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 28;
      stan::math::validate_non_negative_index("W", "J", J);
      current_statement__ = 29;
      stan::math::validate_non_negative_index("W", "K", K);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "W", "double",
        std::vector<size_t>{static_cast<size_t>(J), static_cast<size_t>(K)});
      W_data__ = Eigen::Matrix<double,-1,-1>::Constant(J, K,
                   std::numeric_limits<double>::quiet_NaN());
      new (&W) Eigen::Map<Eigen::Matrix<double,-1,-1>>(W_data__.data(), J, K);
      {
        std::vector<local_scalar_t__> W_flat__;
        current_statement__ = 30;
        W_flat__ = context__.vals_r("W");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            stan::model::assign(W, W_flat__[(pos__ - 1)],
              "assigning variable W", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 31;
      stan::math::validate_non_negative_index("m", "I", I);
      current_statement__ = 32;
      m = std::vector<int>(I, std::numeric_limits<int>::min());
      current_statement__ = 33;
      stan::math::validate_non_negative_index("pos", "I", I);
      current_statement__ = 34;
      pos = std::vector<int>(I, std::numeric_limits<int>::min());
      current_statement__ = 35;
      stan::math::validate_non_negative_index("adj", "K", K);
      current_statement__ = 36;
      adj_data__ = Eigen::Matrix<double,-1,-1>::Constant(2, K,
                     std::numeric_limits<double>::quiet_NaN());
      new (&adj) Eigen::Map<Eigen::Matrix<double,-1,-1>>(adj_data__.data(),
        2, K);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("W_adj", "J", J);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("W_adj", "K", K);
      current_statement__ = 39;
      W_adj_data__ = Eigen::Matrix<double,-1,-1>::Constant(J, K,
                       std::numeric_limits<double>::quiet_NaN());
      new (&W_adj)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(W_adj_data__.data(), J, K);
      current_statement__ = 40;
      stan::model::assign(m, stan::math::rep_array(0, I),
        "assigning variable m");
      current_statement__ = 45;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 43;
        if (stan::math::logical_gt(
              stan::model::rvalue(y, "y", stan::model::index_uni(n)),
              stan::model::rvalue(m, "m",
                stan::model::index_uni(
                  stan::model::rvalue(ii, "ii", stan::model::index_uni(n)))))) {
          current_statement__ = 41;
          stan::model::assign(m,
            stan::model::rvalue(y, "y", stan::model::index_uni(n)),
            "assigning variable m",
            stan::model::index_uni(
              stan::model::rvalue(ii, "ii", stan::model::index_uni(n))));
        }
      }
      current_statement__ = 46;
      stan::model::assign(pos, 1, "assigning variable pos",
        stan::model::index_uni(1));
      current_statement__ = 49;
      for (int i = 2; i <= I; ++i) {
        current_statement__ = 47;
        stan::model::assign(pos,
          (stan::model::rvalue(m, "m", stan::model::index_uni((i - 1))) +
          stan::model::rvalue(pos, "pos", stan::model::index_uni((i - 1)))),
          "assigning variable pos", stan::model::index_uni(i));
      }
      current_statement__ = 50;
      stan::model::assign(adj, obtain_adjustments(W, pstream__),
        "assigning variable adj");
      current_statement__ = 55;
      for (int k = 1; k <= K; ++k) {
        current_statement__ = 53;
        for (int j = 1; j <= J; ++j) {
          current_statement__ = 51;
          stan::model::assign(W_adj,
            ((stan::model::rvalue(W, "W", stan::model::index_uni(j),
                stan::model::index_uni(k)) -
            stan::model::rvalue(adj, "adj", stan::model::index_uni(1),
              stan::model::index_uni(k))) /
            stan::model::rvalue(adj, "adj", stan::model::index_uni(2),
              stan::model::index_uni(k))), "assigning variable W_adj",
            stan::model::index_uni(j), stan::model::index_uni(k));
        }
      }
      current_statement__ = 56;
      stan::math::validate_non_negative_index("alpha", "I", I);
      current_statement__ = 57;
      beta_free_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 57;
      beta_free_1dim__ = (stan::math::sum(m) - 1);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("beta_free", "sum(m) - 1",
        beta_free_1dim__);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("theta", "J", J);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("lambda_adj", "K", K);
      current_statement__ = 60;
      beta_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 60;
      beta_1dim__ = stan::math::sum(m);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("beta", "sum(m)", beta_1dim__);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("lambda", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = I + beta_free_1dim__ + J + K;
  }
  inline std::string model_name() const final {
    return "gpcm_latent_reg_irt_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.39.0",
             "stancflags = "};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "gpcm_latent_reg_irt_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto alpha =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, I);
      current_statement__ = 2;
      auto beta_free =
        in__.template read<
          Eigen::Matrix<local_scalar_t__,-1,1>>(beta_free_1dim__);
      current_statement__ = 3;
      auto theta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(J);
      current_statement__ = 4;
      auto lambda_adj =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(beta_1dim__,
          DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(beta, beta_free, "assigning variable beta",
        stan::model::index_min_max(1, (stan::math::sum(m) - 1)));
      current_statement__ = 8;
      stan::model::assign(beta, (-(1) * stan::math::sum(beta_free)),
        "assigning variable beta", stan::model::index_uni(stan::math::sum(m)));
      {
        current_statement__ = 11;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(alpha,
                         static_cast<double>(1), static_cast<double>(1)));
        current_statement__ = 12;
        lp_accum__.add(stan::math::normal_lpdf<false>(beta,
                         static_cast<double>(0), static_cast<double>(3)));
        current_statement__ = 13;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(theta,
                         stan::math::multiply(W_adj, lambda_adj),
                         static_cast<double>(1)));
        current_statement__ = 14;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(lambda_adj,
                         static_cast<double>(3), static_cast<double>(0),
                         static_cast<double>(1)));
        current_statement__ = 17;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 15;
          lp_accum__.add(pcm(
                           stan::model::rvalue(y, "y",
                             stan::model::index_uni(n)),
                           (stan::model::rvalue(theta, "theta",
                              stan::model::index_uni(
                                stan::model::rvalue(jj, "jj",
                                  stan::model::index_uni(n)))) *
                           stan::model::rvalue(alpha, "alpha",
                             stan::model::index_uni(
                               stan::model::rvalue(ii, "ii",
                                 stan::model::index_uni(n))))),
                           stan::math::segment(beta,
                             stan::model::rvalue(pos, "pos",
                               stan::model::index_uni(
                                 stan::model::rvalue(ii, "ii",
                                   stan::model::index_uni(n)))),
                             stan::model::rvalue(m, "m",
                               stan::model::index_uni(
                                 stan::model::rvalue(ii, "ii",
                                   stan::model::index_uni(n))))), pstream__));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "gpcm_latent_reg_irt_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto alpha =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, I);
      current_statement__ = 2;
      auto beta_free =
        in__.template read<
          Eigen::Matrix<local_scalar_t__,-1,1>>(beta_free_1dim__);
      current_statement__ = 3;
      auto theta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(J);
      current_statement__ = 4;
      auto lambda_adj =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(beta_1dim__,
          DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(beta, beta_free, "assigning variable beta",
        stan::model::index_min_max(1, (stan::math::sum(m) - 1)));
      current_statement__ = 8;
      stan::model::assign(beta, (-(1) * stan::math::sum(beta_free)),
        "assigning variable beta", stan::model::index_uni(stan::math::sum(m)));
      {
        current_statement__ = 11;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(alpha,
                         static_cast<double>(1), static_cast<double>(1)));
        current_statement__ = 12;
        lp_accum__.add(stan::math::normal_lpdf<false>(beta,
                         static_cast<double>(0), static_cast<double>(3)));
        current_statement__ = 13;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(theta,
                         stan::math::multiply(W_adj, lambda_adj),
                         static_cast<double>(1)));
        current_statement__ = 14;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(lambda_adj,
                         static_cast<double>(3), static_cast<double>(0),
                         static_cast<double>(1)));
        current_statement__ = 17;
        {
          current_statement__ = 15;
          auto pcm_terms__ = stan::math::pcm_lpdf_gathered<propto__>(
              y, theta, jj, alpha, ii, beta, pos, m);
          for (const auto& pcm_term__ : pcm_terms__) {
            lp_accum__.add(pcm_term__);
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "gpcm_latent_reg_irt_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto alpha =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, I);
      current_statement__ = 2;
      auto beta_free =
        in__.template read<
          Eigen::Matrix<local_scalar_t__,-1,1>>(beta_free_1dim__);
      current_statement__ = 3;
      auto theta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(J);
      current_statement__ = 4;
      auto lambda_adj =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(beta_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(alpha);
      out__.write(beta_free);
      out__.write(theta);
      out__.write(lambda_adj);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 7;
      stan::model::assign(beta, beta_free, "assigning variable beta",
        stan::model::index_min_max(1, (stan::math::sum(m) - 1)));
      current_statement__ = 8;
      stan::model::assign(beta, (-(1) * stan::math::sum(beta_free)),
        "assigning variable beta", stan::model::index_uni(stan::math::sum(m)));
      if (emit_transformed_parameters__) {
        out__.write(beta);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> lambda =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 9;
      stan::model::assign(lambda,
        stan::math::elt_divide(
          stan::model::rvalue(lambda_adj, "lambda_adj",
            stan::model::index_min_max(2, K)),
          stan::math::to_vector(
            stan::model::rvalue(adj, "adj", stan::model::index_uni(2),
              stan::model::index_min_max(2, K)))),
        "assigning variable lambda", stan::model::index_min_max(2, K));
      current_statement__ = 10;
      stan::model::assign(lambda,
        (stan::math::multiply(
           stan::model::rvalue(W_adj, "W_adj", stan::model::index_uni(1),
             stan::model::index_min_max(1, K)),
           stan::model::rvalue(lambda_adj, "lambda_adj",
             stan::model::index_min_max(1, K))) -
        stan::math::multiply(
          stan::model::rvalue(W, "W", stan::model::index_uni(1),
            stan::model::index_min_max(2, K)),
          stan::model::rvalue(lambda, "lambda",
            stan::model::index_min_max(2, K)))), "assigning variable lambda",
        stan::model::index_uni(1));
      out__.write(lambda);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(I, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(alpha,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(I),
        "assigning variable alpha");
      out__.write_free_lb(0, alpha);
      Eigen::Matrix<local_scalar_t__,-1,1> beta_free =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(beta_free_1dim__,
          DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta_free,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(beta_free_1dim__),
        "assigning variable beta_free");
      out__.write(beta_free);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(theta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable theta");
      out__.write(theta);
      Eigen::Matrix<local_scalar_t__,-1,1> lambda_adj =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(lambda_adj,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable lambda_adj");
      out__.write(lambda_adj);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{static_cast<size_t>(I)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta_free",
        "double", std::vector<size_t>{static_cast<size_t>(beta_free_1dim__)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "theta", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "lambda_adj",
        "double", std::vector<size_t>{static_cast<size_t>(K)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(I, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> alpha_flat__;
        current_statement__ = 1;
        alpha_flat__ = context__.vals_r("alpha");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
          stan::model::assign(alpha, alpha_flat__[(pos__ - 1)],
            "assigning variable alpha", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, alpha);
      Eigen::Matrix<local_scalar_t__,-1,1> beta_free =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(beta_free_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_free_flat__;
        current_statement__ = 2;
        beta_free_flat__ = context__.vals_r("beta_free");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= beta_free_1dim__; ++sym1__) {
          stan::model::assign(beta_free, beta_free_flat__[(pos__ - 1)],
            "assigning variable beta_free", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta_free);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> theta_flat__;
        current_statement__ = 3;
        theta_flat__ = context__.vals_r("theta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          stan::model::assign(theta, theta_flat__[(pos__ - 1)],
            "assigning variable theta", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(theta);
      Eigen::Matrix<local_scalar_t__,-1,1> lambda_adj =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> lambda_adj_flat__;
        current_statement__ = 4;
        lambda_adj_flat__ = context__.vals_r("lambda_adj");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          stan::model::assign(lambda_adj, lambda_adj_flat__[(pos__ - 1)],
            "assigning variable lambda_adj", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(lambda_adj);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha", "beta_free", "theta",
                "lambda_adj"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"beta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"lambda"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(I)},
                std::vector<size_t>{static_cast<size_t>(beta_free_1dim__)},
                std::vector<size_t>{static_cast<size_t>(J)},
                std::vector<size_t>{static_cast<size_t>(K)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(beta_1dim__)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(K)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= beta_free_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_free" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "lambda_adj" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= beta_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "lambda" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= beta_free_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta_free" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "lambda_adj" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= beta_1dim__; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "lambda" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(I) + "},\"block\":\"parameters\"},{\"name\":\"beta_free\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(beta_free_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"lambda_adj\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(beta_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(I) + "},\"block\":\"parameters\"},{\"name\":\"beta_free\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(beta_free_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"lambda_adj\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(beta_1dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = I + beta_free_1dim__ + J + K;
    const size_t num_transformed = emit_transformed_parameters *
      (beta_1dim__);
    const size_t num_gen_quantities = emit_generated_quantities * (K);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = I + beta_free_1dim__ + J + K;
    const size_t num_transformed = emit_transformed_parameters *
      (beta_1dim__);
    const size_t num_gen_quantities = emit_generated_quantities * (K);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = gpcm_latent_reg_irt_model_namespace::gpcm_latent_reg_irt_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return gpcm_latent_reg_irt_model_namespace::profiles__;
}
#endif